import { Link } from "react-router-dom"
import { ArrowLeft } from "lucide-react"
import { Header } from "@/components/Header"
import { Footer } from "@/components/Footer"

export function CookiesPage() {
  return (
    <div className="min-h-screen bg-background flex flex-col">
      <Header />

      <main className="max-w-2xl mx-auto px-4 py-8 flex-1 w-full">
        <Link
          to="/"
          className="inline-flex items-center gap-1.5 text-xs text-muted-foreground hover:text-foreground transition-colors mb-6"
        >
          <ArrowLeft className="size-3" />
          Back to feed
        </Link>

        <h1 className="text-2xl font-semibold tracking-tight mb-1">Cookie Policy</h1>
        <p className="text-xs text-muted-foreground mb-2">Last updated: 24 June 2026</p>
        <p className="text-xs text-muted-foreground mb-2">Contact: clarviodesigners@gmail.com</p>
        <p className="text-xs text-muted-foreground mb-6">Website: buildboard.pages.dev</p>

        <div className="bg-muted/30 border border-border/50 rounded-md p-4 mb-8">
          <p className="text-xs text-muted-foreground">
            <strong>Notice:</strong> By using Buildboard in any way — whether or not you create an account — you agree to this Cookie Policy. Use of this website constitutes acceptance of all policies.
          </p>
        </div>

        <div className="space-y-8">
          <section>
            <h2 className="text-base font-semibold text-foreground mb-3">1. What This Policy Covers</h2>
            <p className="text-sm text-muted-foreground leading-relaxed">
              This Cookie Policy explains what cookies and similar technologies Buildboard uses, why we use them, and how you can control them.
            </p>
            <p className="text-sm text-muted-foreground leading-relaxed mt-2">
              Buildboard is committed to not tracking you for advertising purposes. We use only the minimum necessary cookies and local storage items required to operate the platform.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-foreground mb-3">2. What Are Cookies and Local Storage?</h2>
            <p className="text-sm text-muted-foreground leading-relaxed">
              <strong>Cookies</strong> are small text files stored in your browser by a website you visit. They allow the website to remember information about your visit.
            </p>
            <p className="text-sm text-muted-foreground leading-relaxed mt-2">
              <strong>Local storage</strong> is a similar technology built into your browser that allows websites to store data locally on your device. Unlike cookies, local storage data is not automatically sent to the server with every request — it stays on your device until you clear it.
            </p>
            <p className="text-sm text-muted-foreground leading-relaxed mt-2">
              Buildboard uses both cookies and local storage, explained in detail below.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-foreground mb-3">3. What Buildboard Stores in Your Browser</h2>

            <h3 className="text-sm font-medium text-foreground mb-2">3.1 Session Token (Cookie)</h3>
            <ul className="text-sm text-muted-foreground leading-relaxed list-disc pl-6">
              <li><strong>What it is:</strong> A secure authentication token generated by Supabase when you log into your account</li>
              <li><strong>Why we use it:</strong> To keep you logged in between page visits without requiring you to enter your password every time</li>
              <li><strong>Duration:</strong> 7 days from your last login, or until you log out</li>
              <li><strong>Who sets it:</strong> Supabase (our authentication and database provider)</li>
              <li><strong>Can you disable it:</strong> If you disable this cookie you will not be able to stay logged in. You can still browse Buildboard anonymously without it.</li>
            </ul>

            <h3 className="text-sm font-medium text-foreground mb-2 mt-4">3.2 Theme Preference (Local Storage)</h3>
            <ul className="text-sm text-muted-foreground leading-relaxed list-disc pl-6">
              <li><strong>What it is:</strong> A simple value storing your chosen display theme — either "light", "dark", or "system"</li>
              <li><strong>Why we use it:</strong> To remember your display preference so you do not have to reset it every visit</li>
              <li><strong>Duration:</strong> Until you clear your browser's local storage or change the setting yourself</li>
              <li><strong>Who sets it:</strong> Buildboard directly</li>
              <li><strong>Can you disable it:</strong> Yes. If cleared, the platform will default to light mode until you set a preference again.</li>
            </ul>

            <h3 className="text-sm font-medium text-foreground mb-2 mt-4">3.3 Guest ID (Local Storage)</h3>
            <ul className="text-sm text-muted-foreground leading-relaxed list-disc pl-6">
              <li><strong>What it is:</strong> A randomly generated unique identifier (UUID) created the first time an anonymous user submits a post</li>
              <li><strong>Why we use it:</strong> To allow anonymous users to delete their own posts and to enforce rate limits without requiring an account. This ID is never shared with other users or displayed anywhere on the platform.</li>
              <li><strong>Duration:</strong> Until you clear your browser's local storage</li>
              <li><strong>Who sets it:</strong> Buildboard directly</li>
              <li><strong>Can you disable it:</strong> If cleared, you will lose the ability to delete your previously submitted anonymous posts. A new Guest ID will be generated the next time you post anonymously.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-base font-semibold text-foreground mb-3">4. What We Do Not Use</h2>
            <p className="text-sm text-muted-foreground leading-relaxed">Buildboard does not use:</p>
            <ul className="text-sm text-muted-foreground leading-relaxed list-disc pl-6 mt-2">
              <li>Advertising cookies of any kind</li>
              <li>Third-party tracking cookies</li>
              <li>Analytics cookies (such as Google Analytics)</li>
              <li>Facebook Pixel or any Meta tracking technology</li>
              <li>Retargeting or behavioural advertising technology</li>
              <li>Browser fingerprinting</li>
              <li>Cross-site tracking of any kind</li>
            </ul>
            <p className="text-sm text-muted-foreground leading-relaxed mt-2">
              We will never add advertising or tracking cookies without updating this policy and notifying registered users.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-foreground mb-3">5. Third-Party Cookies</h2>
            <p className="text-sm text-muted-foreground leading-relaxed">
              Buildboard uses Supabase as our authentication and database provider. Supabase may set its own session-related cookies as part of managing authentication. These cookies are strictly functional and are not used for advertising or tracking. You can read Supabase's cookie and privacy practices at supabase.com/privacy.
            </p>
            <p className="text-sm text-muted-foreground leading-relaxed mt-2">
              No other third-party services set cookies on Buildboard.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-foreground mb-3">6. How to Control and Clear Cookies</h2>
            <p className="text-sm text-muted-foreground leading-relaxed">
              You can control, clear, or block cookies and local storage through your browser settings. Here is how to do it in common browsers:
            </p>
            <ul className="text-sm text-muted-foreground leading-relaxed list-none mt-3 space-y-2">
              <li><strong>Google Chrome:</strong> Settings → Privacy and Security → Clear Browsing Data → select Cookies and Site Data and Local Storage</li>
              <li><strong>Mozilla Firefox:</strong> Settings → Privacy &amp; Security → Cookies and Site Data → Clear Data</li>
              <li><strong>Safari:</strong> Settings → Safari → Advanced → Website Data → Remove All Website Data</li>
              <li><strong>Microsoft Edge:</strong> Settings → Privacy, Search, and Services → Clear Browsing Data → Cookies and Other Site Data</li>
              <li><strong>On mobile (Chrome):</strong> Settings → Privacy → Clear Browsing Data</li>
            </ul>
            <p className="text-sm text-muted-foreground leading-relaxed mt-3">
              Please note that clearing cookies and local storage will:
            </p>
            <ul className="text-sm text-muted-foreground leading-relaxed list-disc pl-6 mt-2">
              <li>Log you out of your Buildboard account</li>
              <li>Reset your theme preference to the default</li>
              <li>Remove your Guest ID, meaning you will no longer be able to delete your anonymous posts</li>
            </ul>
          </section>

          <section>
            <h2 className="text-base font-semibold text-foreground mb-3">7. Changes to This Policy</h2>
            <p className="text-sm text-muted-foreground leading-relaxed">
              We may update this Cookie Policy from time to time. When we make changes, we will update the "Last updated" date at the top of this document. Significant changes will be communicated to registered users by email.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-foreground mb-3">8. Contact Us</h2>
            <p className="text-sm text-muted-foreground leading-relaxed">
              If you have any questions about how Buildboard uses cookies or local storage, please contact us at:
            </p>
            <p className="text-sm text-muted-foreground leading-relaxed mt-2">
              <strong>Email:</strong> clarviodesigners@gmail.com<br />
              <strong>Website:</strong> buildboard.pages.dev
            </p>
          </section>
        </div>
      </main>

      <Footer />
    </div>
  )
}
