import { Link } from "react-router-dom"
import { ArrowLeft } from "lucide-react"
import { Header } from "@/components/Header"
import { Footer } from "@/components/Footer"

export function PrivacyPage() {
  return (
    <div className="min-h-screen bg-background flex flex-col">
      <Header />

      <main className="max-w-2xl mx-auto px-4 py-8 flex-1 w-full">
        <Link
          to="/"
          className="inline-flex items-center gap-1.5 text-xs text-muted-foreground hover:text-foreground transition-colors mb-6"
        >
          <ArrowLeft className="size-3" />
          Back to feed
        </Link>

        <h1 className="text-2xl font-semibold tracking-tight mb-1">Privacy Policy</h1>
        <p className="text-xs text-muted-foreground mb-2">Last updated: June 2026</p>
        <p className="text-xs text-muted-foreground mb-2">Contact: clarviodesigners@gmail.com</p>
        <p className="text-xs text-muted-foreground mb-6">Website: buildboard.pages.dev</p>

        <div className="bg-muted/30 border border-border/50 rounded-md p-4 mb-8">
          <p className="text-xs text-muted-foreground">
            <strong>Notice:</strong> By using Buildboard in any way — whether or not you create an account — you agree to this Privacy Policy. Simply visiting or using this website constitutes your acceptance of these terms.
          </p>
        </div>

        <div className="space-y-8">
          <section>
            <h2 className="text-base font-semibold text-foreground mb-3">1. Who We Are</h2>
            <p className="text-sm text-muted-foreground leading-relaxed">
              Buildboard ("we", "us", "our") is a public platform where builders and creators share what they are working on. Buildboard is operated as an independent platform based in India. For any privacy-related concerns, you may contact us at clarviodesigners@gmail.com.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-foreground mb-3">2. What Information We Collect</h2>

            <h3 className="text-sm font-medium text-foreground mb-2">2.1 Information You Provide Directly</h3>
            <p className="text-sm text-muted-foreground leading-relaxed font-medium mt-3">If you create an account:</p>
            <ul className="text-sm text-muted-foreground leading-relaxed list-disc pl-6">
              <li>Email address (required for account creation and verification)</li>
              <li>Display name or username (chosen by you, 3–20 characters)</li>
              <li>Profile picture (uploaded voluntarily, optional)</li>
              <li>Bio (optional, max 150 characters)</li>
              <li>Pronouns (optional)</li>
              <li>External platform links such as GitHub, YouTube, Instagram, LinkedIn, Twitter/X, Discord, or a personal website URL (all optional)</li>
            </ul>

            <p className="text-sm text-muted-foreground leading-relaxed font-medium mt-4">Content you create:</p>
            <ul className="text-sm text-muted-foreground leading-relaxed list-disc pl-6">
              <li>Posts including titles, descriptions, tags, and any media files (images or videos) you upload</li>
              <li>Comments you leave on posts</li>
              <li>Reports you submit about other users or content</li>
            </ul>

            <p className="text-sm text-muted-foreground leading-relaxed font-medium mt-4">If you remain anonymous (no account):</p>
            <ul className="text-sm text-muted-foreground leading-relaxed list-disc pl-6">
              <li>You are not required to provide any personal information to post or comment</li>
              <li>A randomly generated Guest ID (a UUID) is created and stored in your browser's localStorage the first time you post</li>
              <li>This Guest ID is never visible to you, other users, or anyone else — it is used only internally to track your posts for rate limiting and to allow you to delete your own content within the same browser</li>
            </ul>

            <h3 className="text-sm font-medium text-foreground mb-2 mt-4">2.2 Information Collected Automatically</h3>
            <ul className="text-sm text-muted-foreground leading-relaxed list-disc pl-6">
              <li><strong>IP address</strong> — collected for rate limiting, abuse prevention, and security purposes. We do not use IP addresses for advertising or sell them to third parties.</li>
              <li><strong>Browser and device information</strong> — basic technical information such as browser type and operating system, collected passively when you use the platform</li>
              <li><strong>Session tokens</strong> — generated by our authentication provider (Supabase) when you log in, stored securely in your browser</li>
            </ul>

            <h3 className="text-sm font-medium text-foreground mb-2 mt-4">2.3 Information We Do Not Collect</h3>
            <p className="text-sm text-muted-foreground leading-relaxed">We do not collect:</p>
            <ul className="text-sm text-muted-foreground leading-relaxed list-disc pl-6">
              <li>Phone numbers</li>
              <li>Mailing or physical addresses</li>
              <li>Payment or billing information</li>
              <li>Date of birth or age (beyond confirming you are 13 or older)</li>
              <li>Real name (your display name is chosen by you and does not need to be your real name)</li>
              <li>Location data beyond your IP address</li>
              <li>Contacts or camera access</li>
              <li>Any data through advertising networks, Facebook Pixel, or retargeting tools</li>
            </ul>
          </section>

          <section>
            <h2 className="text-base font-semibold text-foreground mb-3">3. How We Use Your Information</h2>
            <p className="text-sm text-muted-foreground leading-relaxed">
              We use the information we collect for the following purposes:
            </p>
            <table className="text-sm text-muted-foreground w-full mt-3 border border-border/50">
              <thead>
                <tr className="border-b border-border/50">
                  <th className="text-left p-2 font-medium">Purpose</th>
                  <th className="text-left p-2 font-medium">Legal Basis (GDPR)</th>
                </tr>
              </thead>
              <tbody>
                <tr className="border-b border-border/50"><td className="p-2">To create and manage your account</td><td className="p-2">Contract</td></tr>
                <tr className="border-b border-border/50"><td className="p-2">To display your posts and profile publicly</td><td className="p-2">Contract</td></tr>
                <tr className="border-b border-border/50"><td className="p-2">To send email verification when you sign up</td><td className="p-2">Contract</td></tr>
                <tr className="border-b border-border/50"><td className="p-2">To send email notifications when someone comments on your post (if enabled)</td><td className="p-2">Consent</td></tr>
                <tr className="border-b border-border/50"><td className="p-2">To enforce rate limits and prevent abuse</td><td className="p-2">Legitimate interest</td></tr>
                <tr className="border-b border-border/50"><td className="p-2">To moderate content for violations of our Community Guidelines</td><td className="p-2">Legitimate interest</td></tr>
                <tr className="border-b border-border/50"><td className="p-2">To investigate reports and take action on violations</td><td className="p-2">Legitimate interest</td></tr>
                <tr className="border-b border-border/50"><td className="p-2">To respond to your support or legal requests</td><td className="p-2">Legal obligation</td></tr>
                <tr><td className="p-2">To improve the platform based on usage patterns</td><td className="p-2">Legitimate interest</td></tr>
              </tbody>
            </table>
            <p className="text-sm text-muted-foreground leading-relaxed mt-3">
              We will never use your information for advertising, profiling for commercial purposes, or sell it to any third party.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-foreground mb-3">4. Third-Party Services That Receive Your Data</h2>
            <p className="text-sm text-muted-foreground leading-relaxed">
              Buildboard uses the following third-party services. By using Buildboard, you acknowledge that your data may be processed by these services as described below.
            </p>

            <h3 className="text-sm font-medium text-foreground mb-2 mt-4">4.1 Supabase</h3>
            <p className="text-sm text-muted-foreground leading-relaxed">
              Supabase is our database, file storage, and authentication provider. All user data — including your email address, display name, posts, comments, profile picture, and session tokens — is stored on Supabase's servers. Supabase is SOC 2 Type 2 compliant and processes data in accordance with their own privacy policy available at supabase.com/privacy.
            </p>

            <h3 className="text-sm font-medium text-foreground mb-2 mt-4">4.2 Google Gemini API</h3>
            <p className="text-sm text-muted-foreground leading-relaxed">
              When you or another user clicks the "Explain This" button on a post, the post's title and description are sent to Google's Gemini API to generate a plain-language explanation. No personal identifying information is sent — only the post content itself. Google processes this data in accordance with their API Terms of Service and Privacy Policy.
            </p>

            <h3 className="text-sm font-medium text-foreground mb-2 mt-4">4.3 OpenAI Moderation API</h3>
            <p className="text-sm text-muted-foreground leading-relaxed">
              Every post title, post description, comment, and uploaded image submitted to Buildboard is automatically sent to OpenAI's Moderation API before being saved. This is to detect and prevent toxic, hateful, harmful, or sexually explicit content. Only the content itself is sent — no account information, email, or personal details are included. OpenAI processes this data in accordance with their API Terms of Service and Privacy Policy.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-foreground mb-3">5. Cookies and Local Storage</h2>

            <h3 className="text-sm font-medium text-foreground mb-2">5.1 What We Store in Your Browser</h3>
            <table className="text-sm text-muted-foreground w-full mt-3 border border-border/50">
              <thead>
                <tr className="border-b border-border/50">
                  <th className="text-left p-2 font-medium">Item</th>
                  <th className="text-left p-2 font-medium">Type</th>
                  <th className="text-left p-2 font-medium">Purpose</th>
                  <th className="text-left p-2 font-medium">Duration</th>
                </tr>
              </thead>
              <tbody>
                <tr className="border-b border-border/50">
                  <td className="p-2">Theme preference (light/dark)</td>
                  <td className="p-2">localStorage</td>
                  <td className="p-2">Remembers your display preference</td>
                  <td className="p-2">Until you clear browser data</td>
                </tr>
                <tr className="border-b border-border/50">
                  <td className="p-2">Guest ID</td>
                  <td className="p-2">localStorage</td>
                  <td className="p-2">Tracks anonymous posts for rate limiting and deletion</td>
                  <td className="p-2">Until you clear browser data</td>
                </tr>
                <tr>
                  <td className="p-2">Session token</td>
                  <td className="p-2">Cookie (Supabase)</td>
                  <td className="p-2">Keeps you logged in</td>
                  <td className="p-2">7 days or until logout</td>
                </tr>
              </tbody>
            </table>

            <h3 className="text-sm font-medium text-foreground mb-2 mt-4">5.2 What We Do Not Use</h3>
            <p className="text-sm text-muted-foreground leading-relaxed">
              We do not use advertising cookies, tracking cookies, third-party analytics cookies, or the Facebook Pixel. We do not use fingerprinting or any cross-site tracking technology.
            </p>

            <h3 className="text-sm font-medium text-foreground mb-2 mt-4">5.3 How to Clear Your Data</h3>
            <p className="text-sm text-muted-foreground leading-relaxed">
              You can clear all locally stored data at any time by clearing your browser's cookies and localStorage through your browser settings. Note that clearing your Guest ID means you will lose the ability to delete your anonymous posts.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-foreground mb-3">6. Data Retention</h2>
            <table className="text-sm text-muted-foreground w-full border border-border/50">
              <thead>
                <tr className="border-b border-border/50">
                  <th className="text-left p-2 font-medium">Data Type</th>
                  <th className="text-left p-2 font-medium">Retention Period</th>
                </tr>
              </thead>
              <tbody>
                <tr className="border-b border-border/50"><td className="p-2">Account data (email, display name, profile)</td><td className="p-2">Until you delete your account</td></tr>
                <tr className="border-b border-border/50"><td className="p-2">Posts and comments</td><td className="p-2">Until you delete them or your account</td></tr>
                <tr className="border-b border-border/50"><td className="p-2">Profile pictures and media uploads</td><td className="p-2">Until you delete them or your account</td></tr>
                <tr className="border-b border-border/50"><td className="p-2">IP address logs for rate limiting</td><td className="p-2">24 hours</td></tr>
                <tr className="border-b border-border/50"><td className="p-2">Login attempt logs</td><td className="p-2">30 days</td></tr>
                <tr className="border-b border-border/50"><td className="p-2">Reports submitted</td><td className="p-2">Until resolved, maximum 90 days</td></tr>
                <tr><td className="p-2">Guest ID in localStorage</td><td className="p-2">Until you clear your browser data</td></tr>
              </tbody>
            </table>
            <p className="text-sm text-muted-foreground leading-relaxed mt-3">
              When you delete your account, all your posts, comments, profile data, and uploaded media are permanently deleted from our systems within 30 days.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-foreground mb-3">7. Your Rights</h2>

            <h3 className="text-sm font-medium text-foreground mb-2">7.1 All Users</h3>
            <ul className="text-sm text-muted-foreground leading-relaxed list-disc pl-6">
              <li><strong>Access</strong> — you may request a copy of all data we hold about you</li>
              <li><strong>Deletion</strong> — you may request deletion of your account and all associated data</li>
              <li><strong>Correction</strong> — you may update your display name, email, bio, and profile picture at any time through Settings</li>
              <li><strong>Download</strong> — logged-in users can export all their posts and comments as a JSON file from Settings &gt; Account &gt; Download Your Data</li>
              <li><strong>Withdraw consent</strong> — you may disable email notifications at any time through Settings &gt; Notifications</li>
            </ul>

            <h3 className="text-sm font-medium text-foreground mb-2 mt-4">7.2 GDPR Rights (European Users)</h3>
            <p className="text-sm text-muted-foreground leading-relaxed">
              If you are located in the European Economic Area (EEA), you have the following additional rights under the General Data Protection Regulation (GDPR):
            </p>
            <ul className="text-sm text-muted-foreground leading-relaxed list-disc pl-6 mt-2">
              <li><strong>Right to access</strong> your personal data</li>
              <li><strong>Right to rectification</strong> of inaccurate data</li>
              <li><strong>Right to erasure</strong> ("right to be forgotten")</li>
              <li><strong>Right to restriction</strong> of processing</li>
              <li><strong>Right to data portability</strong></li>
              <li><strong>Right to object</strong> to processing based on legitimate interest</li>
              <li><strong>Right to lodge a complaint</strong> with your local supervisory authority</li>
            </ul>
            <p className="text-sm text-muted-foreground leading-relaxed mt-2">
              To exercise any of these rights, contact us at clarviodesigners@gmail.com. We will respond within 30 days.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-foreground mb-3">8. Children's Privacy</h2>
            <p className="text-sm text-muted-foreground leading-relaxed">
              Buildboard is not intended for use by anyone under the age of 13. We do not knowingly collect personal information from children under 13. If you are a parent or guardian and believe your child has provided personal information on Buildboard, please contact us immediately at clarviodesigners@gmail.com and we will delete that information promptly.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-foreground mb-3">9. Data Security</h2>
            <p className="text-sm text-muted-foreground leading-relaxed">
              We take reasonable technical and organizational measures to protect your data, including:
            </p>
            <ul className="text-sm text-muted-foreground leading-relaxed list-disc pl-6 mt-2">
              <li>All data transmitted between your browser and our servers is encrypted using HTTPS/TLS</li>
              <li>Passwords are never stored in plain text — they are hashed by Supabase Auth</li>
              <li>Database access is protected by Row Level Security (RLS) policies so users can only access their own data</li>
              <li>Media files are stored in private Supabase Storage buckets served via signed URLs</li>
              <li>API keys and sensitive credentials are stored as server-side environment secrets, never exposed to the client</li>
            </ul>
            <p className="text-sm text-muted-foreground leading-relaxed mt-2">
              However, no system is completely secure. In the event of a data breach that affects your personal information, we will notify affected users by email within 72 hours of becoming aware of the breach, in accordance with GDPR requirements.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-foreground mb-3">10. Data Breach Notification</h2>
            <p className="text-sm text-muted-foreground leading-relaxed">
              If a data breach occurs that is likely to result in a risk to your rights and freedoms, we will:
            </p>
            <ul className="text-sm text-muted-foreground leading-relaxed list-disc pl-6 mt-2">
              <li>Notify affected users by email within 72 hours</li>
              <li>Describe the nature of the breach and what data was affected</li>
              <li>Describe the steps we are taking to address it</li>
              <li>Provide contact information for further questions</li>
            </ul>
          </section>

          <section>
            <h2 className="text-base font-semibold text-foreground mb-3">11. Changes to This Policy</h2>
            <p className="text-sm text-muted-foreground leading-relaxed">
              We may update this Privacy Policy from time to time. When we make significant changes, we will notify registered users by email and update the "Last updated" date at the top of this document. Continued use of Buildboard after changes are posted constitutes your acceptance of the updated policy.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-foreground mb-3">12. Contact Us</h2>
            <p className="text-sm text-muted-foreground leading-relaxed">
              For any privacy-related questions, data requests, or concerns, contact us at:
            </p>
            <p className="text-sm text-muted-foreground leading-relaxed mt-2">
              <strong>Email:</strong> clarviodesigners@gmail.com<br />
              <strong>Website:</strong> buildboard.pages.dev
            </p>
            <p className="text-sm text-muted-foreground leading-relaxed mt-2">
              We aim to respond to all privacy-related requests within 30 days.
            </p>
          </section>
        </div>
      </main>

      <Footer />
    </div>
  )
}
